// finance-tracker/frontend/react/src/pages/Dashboard.tsx
import { useEffect, useState } from 'react'
import { Card, CardContent, Typography, Grid, Table, TableHead, TableRow, TableCell, TableBody, Chip } from '@mui/material'
import { analytics } from '../api'

export default function Dashboard() {
  const [summary, setSummary] = useState<any>({})
  const [balances, setBalances] = useState<any[]>([])
  const [byCategory, setByCategory] = useState<any[]>([])

  useEffect(() => {
    Promise.all([analytics.summary(), analytics.accountBalances(), analytics.byCategory()])
      .then(([s, b, c]) => {
        setSummary(s.data.data || {})
        setBalances(b.data.data || [])
        setByCategory(c.data.data || [])
      })
  }, [])

  return (
    <>
      <Typography variant="h4" gutterBottom>Dashboard</Typography>
      <Grid container spacing={2} sx={{ mb: 4 }}>
        <Grid size={4}><Card sx={{ bgcolor: '#e8f5e9' }}><CardContent><Typography variant="h6">Income</Typography><Typography variant="h4">${summary.income?.toFixed(2) || '0.00'}</Typography></CardContent></Card></Grid>
        <Grid size={4}><Card sx={{ bgcolor: '#ffebee' }}><CardContent><Typography variant="h6">Expenses</Typography><Typography variant="h4">${summary.expense?.toFixed(2) || '0.00'}</Typography></CardContent></Card></Grid>
        <Grid size={4}><Card sx={{ bgcolor: '#e3f2fd' }}><CardContent><Typography variant="h6">Net</Typography><Typography variant="h4">${summary.net?.toFixed(2) || '0.00'}</Typography></CardContent></Card></Grid>
      </Grid>

      <Typography variant="h5" gutterBottom>Account Balances</Typography>
      <Table sx={{ mb: 4 }}>
        <TableHead><TableRow><TableCell>Account</TableCell><TableCell>Type</TableCell><TableCell>Balance</TableCell></TableRow></TableHead>
        <TableBody>{balances.map((a, i) => <TableRow key={i}><TableCell>{a.name}</TableCell><TableCell>{a.type}</TableCell><TableCell>${a.balance}</TableCell></TableRow>)}</TableBody>
      </Table>

      <Typography variant="h5" gutterBottom>Spending by Category</Typography>
      <Table>
        <TableHead><TableRow><TableCell>Category</TableCell><TableCell>Total</TableCell></TableRow></TableHead>
        <TableBody>{byCategory.map((c, i) => <TableRow key={i}><TableCell><Chip label={c.name} sx={{ bgcolor: c.color, color: '#fff' }} size="small" /></TableCell><TableCell>${parseFloat(c.total).toFixed(2)}</TableCell></TableRow>)}</TableBody>
      </Table>
    </>
  )
}

// finance-tracker/frontend/angular/src/app/dashboard/dashboard.ts
import { Component, OnInit } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { MatTableModule } from '@angular/material/table';
import { analytics } from '../api';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [MatCardModule, MatTableModule],
  template: `
    <h1>Dashboard</h1>
    <div style="display:flex;gap:16px;margin-bottom:24px">
      <mat-card style="flex:1;background:#e8f5e9"><mat-card-content><h3>Income</h3><h2>\${{ summary.income?.toFixed(2) || '0.00' }}</h2></mat-card-content></mat-card>
      <mat-card style="flex:1;background:#ffebee"><mat-card-content><h3>Expenses</h3><h2>\${{ summary.expense?.toFixed(2) || '0.00' }}</h2></mat-card-content></mat-card>
      <mat-card style="flex:1;background:#e3f2fd"><mat-card-content><h3>Net</h3><h2>\${{ summary.net?.toFixed(2) || '0.00' }}</h2></mat-card-content></mat-card>
    </div>
    <h2>Account Balances</h2>
    <table mat-table [dataSource]="balances" style="width:100%">
      <ng-container matColumnDef="name"><th mat-header-cell *matHeaderCellDef>Account</th><td mat-cell *matCellDef="let a">{{ a.name }}</td></ng-container>
      <ng-container matColumnDef="type"><th mat-header-cell *matHeaderCellDef>Type</th><td mat-cell *matCellDef="let a">{{ a.type }}</td></ng-container>
      <ng-container matColumnDef="balance"><th mat-header-cell *matHeaderCellDef>Balance</th><td mat-cell *matCellDef="let a">\${{ a.balance }}</td></ng-container>
      <tr mat-header-row *matHeaderRowDef="['name','type','balance']"></tr>
      <tr mat-row *matRowDef="let row; columns: ['name','type','balance']"></tr>
    </table>
  `
})
export class DashboardComponent implements OnInit {
  summary: any = {};
  balances: any[] = [];

  async ngOnInit() {
    const [s, b] = await Promise.all([analytics.summary(), analytics.accountBalances()]);
    this.summary = s.data.data || {};
    this.balances = b.data.data || [];
  }
}
