// finance-tracker/frontend/angular/src/app/accounts/accounts.ts
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MatTableModule } from '@angular/material/table';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { accounts } from '../api';

@Component({
  selector: 'app-accounts',
  standalone: true,
  imports: [FormsModule, MatTableModule, MatFormFieldModule, MatInputModule, MatSelectModule, MatButtonModule, MatIconModule],
  template: `
    <h1>Accounts</h1>
    <div style="display:flex;gap:8px;margin-bottom:16px">
      <mat-form-field><input matInput placeholder="Name" [(ngModel)]="form.name"></mat-form-field>
      <mat-form-field><mat-select [(ngModel)]="form.type"><mat-option value="checking">Checking</mat-option><mat-option value="savings">Savings</mat-option><mat-option value="credit">Credit</mat-option><mat-option value="cash">Cash</mat-option></mat-select></mat-form-field>
      <mat-form-field><input matInput type="number" placeholder="Balance" [(ngModel)]="form.balance"></mat-form-field>
      <button mat-raised-button color="primary" (click)="add()">Add</button>
    </div>
    <table mat-table [dataSource]="items" style="width:100%">
      <ng-container matColumnDef="name"><th mat-header-cell *matHeaderCellDef>Name</th><td mat-cell *matCellDef="let a">{{ a.name }}</td></ng-container>
      <ng-container matColumnDef="type"><th mat-header-cell *matHeaderCellDef>Type</th><td mat-cell *matCellDef="let a">{{ a.type }}</td></ng-container>
      <ng-container matColumnDef="balance"><th mat-header-cell *matHeaderCellDef>Balance</th><td mat-cell *matCellDef="let a">\${{ a.balance }}</td></ng-container>
      <ng-container matColumnDef="actions"><th mat-header-cell *matHeaderCellDef></th><td mat-cell *matCellDef="let a"><button mat-icon-button color="warn" (click)="remove(a.id)"><mat-icon>delete</mat-icon></button></td></ng-container>
      <tr mat-header-row *matHeaderRowDef="['name','type','balance','actions']"></tr>
      <tr mat-row *matRowDef="let row; columns: ['name','type','balance','actions']"></tr>
    </table>
  `
})
export class AccountsComponent implements OnInit {
  items: any[] = [];
  form = { name: '', type: 'checking', balance: '0' };

  async ngOnInit() { await this.load(); }

  async load() { this.items = (await accounts.list()).data.data || []; }

  async add() {
    if (!this.form.name) return;
    await accounts.create(this.form.name, this.form.type, parseFloat(this.form.balance));
    this.form = { name: '', type: 'checking', balance: '0' };
    await this.load();
  }

  async remove(id: number) { await accounts.remove(id); await this.load(); }
}

// finance-tracker/frontend/react/src/pages/Accounts.tsx
import { useEffect, useState } from 'react'
import { Typography, Table, TableHead, TableRow, TableCell, TableBody, TextField, Button, Select, MenuItem, IconButton, Box } from '@mui/material'
import DeleteIcon from '@mui/icons-material/Delete'
import { accounts } from '../api'

export default function Accounts() {
  const [items, setItems] = useState<any[]>([])
  const [form, setForm] = useState({ name: '', type: 'checking', balance: '0' })

  const load = () => accounts.list().then(r => setItems(r.data.data || []))
  useEffect(() => { load() }, [])

  const add = async () => {
    if (!form.name) return
    await accounts.create(form.name, form.type, parseFloat(form.balance))
    setForm({ name: '', type: 'checking', balance: '0' })
    load()
  }

  return (
    <>
      <Typography variant="h4" gutterBottom>Accounts</Typography>
      <Box sx={{ display: 'flex', gap: 1, mb: 3 }}>
        <TextField size="small" placeholder="Name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} />
        <Select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })} size="small">
          <MenuItem value="checking">Checking</MenuItem><MenuItem value="savings">Savings</MenuItem><MenuItem value="credit">Credit</MenuItem><MenuItem value="cash">Cash</MenuItem>
        </Select>
        <TextField size="small" type="number" placeholder="Balance" value={form.balance} onChange={e => setForm({ ...form, balance: e.target.value })} />
        <Button variant="contained" onClick={add}>Add</Button>
      </Box>
      <Table>
        <TableHead><TableRow><TableCell>Name</TableCell><TableCell>Type</TableCell><TableCell>Balance</TableCell><TableCell></TableCell></TableRow></TableHead>
        <TableBody>{items.map(a => <TableRow key={a.id}><TableCell>{a.name}</TableCell><TableCell>{a.type}</TableCell><TableCell>${a.balance}</TableCell><TableCell><IconButton color="error" onClick={() => { accounts.remove(a.id).then(load) }}><DeleteIcon /></IconButton></TableCell></TableRow>)}</TableBody>
      </Table>
    </>
  )
}
