// finance-tracker/frontend/angular/src/app/login/login.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';
import { auth } from '../api';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [FormsModule, MatCardModule, MatFormFieldModule, MatInputModule, MatButtonModule],
  template: `
    <mat-card style="max-width:400px;margin:40px auto">
      <mat-card-header><mat-card-title>Login</mat-card-title></mat-card-header>
      <mat-card-content>
        @if (error) { <p style="color:red">{{ error }}</p> }
        <mat-form-field style="width:100%"><input matInput placeholder="Email" [(ngModel)]="email"></mat-form-field>
        <mat-form-field style="width:100%"><input matInput type="password" placeholder="Password" [(ngModel)]="password"></mat-form-field>
      </mat-card-content>
      <mat-card-actions><button mat-raised-button color="primary" (click)="login()" style="width:100%">Login</button></mat-card-actions>
    </mat-card>
  `
})
export class LoginComponent {
  email = 'demo@example.com';
  password = 'demo123';
  error = '';

  async login() {
    try {
      await auth.login(this.email, this.password);
      window.location.href = '/';
    } catch (e: any) {
      this.error = e.response?.data?.message || 'Login failed';
    }
  }
}

// finance-tracker/frontend/react/src/pages/Login.tsx
import { useState } from 'react'
import { TextField, Button, Card, CardContent, Typography, Alert } from '@mui/material'
import { auth } from '../api'

export default function Login({ onLogin }: { onLogin: () => void }) {
  const [email, setEmail] = useState('demo@example.com')
  const [password, setPassword] = useState('demo123')
  const [error, setError] = useState('')

  const submit = async () => {
    try {
      await auth.login(email, password)
      window.location.href = '/'
    } catch (e: any) {
      setError(e.response?.data?.message || 'Login failed')
    }
  }

  return (
    <Card sx={{ maxWidth: 400, mx: 'auto', mt: 10 }}>
      <CardContent>
        <Typography variant="h5" gutterBottom>Login</Typography>
        {error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}
        <TextField fullWidth label="Email" value={email} onChange={e => setEmail(e.target.value)} sx={{ mb: 2 }} />
        <TextField fullWidth label="Password" type="password" value={password} onChange={e => setPassword(e.target.value)} sx={{ mb: 2 }} />
        <Button variant="contained" fullWidth onClick={submit}>Login</Button>
      </CardContent>
    </Card>
  )
}
