// finance-tracker/frontend/angular/src/app/app.ts
import { Component, OnInit } from '@angular/core';
import { RouterOutlet, RouterLink } from '@angular/router';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatButtonModule } from '@angular/material/button';
import { auth } from './api';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, RouterLink, MatToolbarModule, MatButtonModule],
  template: `
    <mat-toolbar color="primary">
      <span>Finance Tracker</span>
      <span style="flex:1"></span>
      @if (loggedIn) {
        <a mat-button routerLink="/">Dashboard</a>
        <a mat-button routerLink="/transactions">Transactions</a>
        <a mat-button routerLink="/accounts">Accounts</a>
        <button mat-button (click)="logout()">Logout</button>
      }
    </mat-toolbar>
    <div style="padding:24px">
      <router-outlet />
    </div>
  `
})
export class AppComponent implements OnInit {
  loggedIn = false;

  async ngOnInit() {
    try {
      await auth.profile();
      this.loggedIn = true;
    } catch {
      this.loggedIn = false;
    }
  }

  logout() {
    document.cookie = 'wf-session=; Max-Age=0; path=/';
    window.location.href = '/login';
  }
}

// finance-tracker/frontend/vue/src/App.vue
<template>
  <v-app>
    <v-app-bar color="primary" dark>
      <v-toolbar-title>Finance Tracker</v-toolbar-title>
      <v-spacer />
      <template v-if="loggedIn">
        <v-btn to="/" text>Dashboard</v-btn>
        <v-btn to="/transactions" text>Transactions</v-btn>
        <v-btn to="/accounts" text>Accounts</v-btn>
        <v-btn to="/budgets" text>Budgets</v-btn>
        <v-btn @click="logout" text>Logout</v-btn>
      </template>
    </v-app-bar>
    <v-main>
      <v-container>
        <router-view />
      </v-container>
    </v-main>
  </v-app>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { auth } from './api'

const router = useRouter()
const loggedIn = ref(false)

onMounted(async () => {
  try {
    await auth.profile()
    loggedIn.value = true
  } catch {
    loggedIn.value = false
    router.push('/login')
  }
})

const logout = () => {
  document.cookie = 'wf-session=; Max-Age=0; path=/'
  loggedIn.value = false
  router.push('/login')
}
</script>
