// finance-tracker/frontend/react/src/App.tsx
import { BrowserRouter, Routes, Route, Link, Navigate } from 'react-router-dom'
import { AppBar, Toolbar, Typography, Button, Container, CssBaseline, ThemeProvider, createTheme } from '@mui/material'
import { useState, useEffect } from 'react'
import { auth } from './api'
import Login from './pages/Login'
import Dashboard from './pages/Dashboard'
import Transactions from './pages/Transactions'
import Accounts from './pages/Accounts'
import Budgets from './pages/Budgets'

const theme = createTheme()

function App() {
  const [loggedIn, setLoggedIn] = useState<boolean | null>(null)

  useEffect(() => {
    auth.profile().then(() => setLoggedIn(true)).catch(() => setLoggedIn(false))
  }, [])

  if (loggedIn === null) return null

  return (
    <ThemeProvider theme={theme}>
      <CssBaseline />
      <BrowserRouter>
        <AppBar position="static">
          <Toolbar>
            <Typography variant="h6" sx={{ flexGrow: 1 }}>Finance Tracker</Typography>
            {loggedIn && <>
              <Button color="inherit" component={Link} to="/">Dashboard</Button>
              <Button color="inherit" component={Link} to="/transactions">Transactions</Button>
              <Button color="inherit" component={Link} to="/accounts">Accounts</Button>
              <Button color="inherit" component={Link} to="/budgets">Budgets</Button>
              <Button color="inherit" onClick={() => { document.cookie = 'wf-session=; Max-Age=0; path=/'; window.location.href = '/login' }}>Logout</Button>
            </>}
          </Toolbar>
        </AppBar>
        <Container sx={{ mt: 4 }}>
          <Routes>
            <Route path="/login" element={<Login onLogin={() => setLoggedIn(true)} />} />
            <Route path="/" element={loggedIn ? <Dashboard /> : <Navigate to="/login" />} />
            <Route path="/transactions" element={loggedIn ? <Transactions /> : <Navigate to="/login" />} />
            <Route path="/accounts" element={loggedIn ? <Accounts /> : <Navigate to="/login" />} />
            <Route path="/budgets" element={loggedIn ? <Budgets /> : <Navigate to="/login" />} />
          </Routes>
        </Container>
      </BrowserRouter>
    </ThemeProvider>
  )
}

export default App

// finance-tracker/frontend/angular/src/app/app.ts
import { Component, OnInit } from '@angular/core';
import { RouterOutlet, RouterLink } from '@angular/router';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatButtonModule } from '@angular/material/button';
import { auth } from './api';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, RouterLink, MatToolbarModule, MatButtonModule],
  template: `
    <mat-toolbar color="primary">
      <span>Finance Tracker</span>
      <span style="flex:1"></span>
      @if (loggedIn) {
        <a mat-button routerLink="/">Dashboard</a>
        <a mat-button routerLink="/transactions">Transactions</a>
        <a mat-button routerLink="/accounts">Accounts</a>
        <button mat-button (click)="logout()">Logout</button>
      }
    </mat-toolbar>
    <div style="padding:24px">
      <router-outlet />
    </div>
  `
})
export class AppComponent implements OnInit {
  loggedIn = false;

  async ngOnInit() {
    try {
      await auth.profile();
      this.loggedIn = true;
    } catch {
      this.loggedIn = false;
    }
  }

  logout() {
    document.cookie = 'wf-session=; Max-Age=0; path=/';
    window.location.href = '/login';
  }
}
